### ISSUE TITLE
Git operations with `git.subprocess=true` fail if hook prints unexpected text

### ISSUE THREAD

**Issue by zx8** [jj-vcs/jj#5610]
JJ should ignore hooks when `git.subprocess=true`, since some of my Git hooks output information.

Example:

```
$ jj git push
Changes to push to origin:
  Move sideways bookmark zx8/ntmyzyrvtzwu from 7de2273ab713 to 1febf55ed2b2
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
Error: Git process failed: Git push output unfamiliar:

 ␛[1;97mhttps://github.com/zx8/jj/commit/1febf55␛[0m

To github.com:zx8/jj.git
+ 1febf55ed2b2a07dc1aaed40bcaed10f672ec532:refs/heads/zx8/ntmyzyrvtzwu 7de2273...1febf55 (forced update)
Done

```

I think disabling Git hooks via the following might help:

```
git -c core.hooksPath=/dev/null
```

**Comment by martinvonz** [comment]
@bsdinis for visibility

**Comment by bsdinis** [comment]
Hi! Thanks for submitting this!
Will try to reproduce and work on a fix. It'll probably come in two waves, a first one to stop it to fail and a second one to forward the git hook output

**Comment by jennings** [comment]
Unless we're _sure_ there aren't bizarre edge cases, it might be safer to suppress hooks for now until we can resolve the issues. For example:

- Will they run properly in a non-colocated repo, since they might assume a Git working copy and a non-bare Git repo?
- If the hook changes files (which is probably bad form for a pre-push hook), do we incorporate those changes in the push, or after?

**Comment by bsdinis** [comment]
> Unless we're sure there aren't bizarre edge cases, it might be safer to suppress hooks for now until we can resolve the issues. For example:

After discussing it, I agree
#5612 should fix it

**Comment by arxanas** [comment]
For additional context, we may change it in the future so that `jj git push` *does* run `pre-push` hooks by default.
- The issue in https://github.com/jj-vcs/jj/issues/3577 is not resolved, but it seems likely that we would eventually support `pre-push` hooks.
- There was additional discussion [in this Discord thread](https://discord.com/channels/968932220549103686/1337163765011185745).

@zx8 By the way, do you think it would be feasible to adjust the `pre-push` hook in your case to write to `stderr`?
